// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '00-scd',
    }
  ],
  basic: [
    {
      type: 'autogenerated',
      dirName: '02-basic',
    }
  ],
};

module.exports = sidebars;
