// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  scd: [
    {
      type: 'autogenerated',
      dirName: '00-scd',
    }
  ],
  starter: [
    {
      type: 'autogenerated',
      dirName: '01-starter',
    }
  ],
  basic: [
    {
      type: 'autogenerated',
      dirName: '02-basic',
    }
  ],
  intermediate: [
    {
      type: 'autogenerated',
      dirName: '03-intermediate',
    }
  ],
};

module.exports = sidebars;
